/**
 * Textos del asistente de precio de ingredientes (wizard + modal edición).
 * Pensados para quien no conozca el sector: preguntas cortas y ejemplos.
 */
export const pricingAssistantCopy = {
  name: {
    title: '¿Cómo se llama el producto?',
    hint: 'Como lo reconoceréis en cocina o almacén. No tiene que coincidir con el nombre del proveedor.',
    continue: 'Siguiente',
  },
  category: {
    title: '¿Qué tipo de cosa es?',
    hint: 'Solo orienta el tipo de medida habitual. Si no está claro, «Comida» u «Otros» sirve.',
    drinks: 'Bebida',
    drinksSub: 'Refrescos, cervezas, vinos, zumos…',
    food: 'Comida / cocina',
    foodSub: 'Carne, verdura, secos, aceite para freír…',
    packaging: 'Envases y bolsas',
    packagingSub: 'Film, tapers, guantes, cartones…',
    cleaning: 'Limpieza',
    cleaningSub: 'Lejía, estropajos, papel…',
    other: 'Otro',
    otherSub: 'Cosas que no encajan arriba',
    skipLater: 'No lo sé aún — seguir',
  },
  invoiceStyle: {
    title: '¿Cómo viene el precio en la factura o albarán?',
    hint: 'Mirad lo que cobra el proveedor: casi siempre sale por peso, litros, caja completa o pieza suelta.',
    perKg: 'Por peso',
    perKgSub: '€ al kilo (o factura en gramos)',
    perL: 'Por litro',
    perLSub: '€ por litro o mililitros',
    perPack: 'Por caja o pack',
    perPackSub: 'Un precio para todo el bulto (ej. caja de 24)',
    perUnit: 'Por pieza suelta',
    perUnitSub: 'Pagáis cada unidad aparte (un saco, una botella…)',
    skipLater: 'Sin precio aún',
  },
  baseMeasure: {
    title: 'Para repartir costes en recetas…',
    hint: '¿Cómo lo vais a medir casi siempre: pesando, con vaso medidor o contando piezas?',
    weight: 'Por peso',
    weightSub: 'Kilos o gramos (sacos, botes…)',
    volume: 'Por líquido',
    volumeSub: 'Litros o mililitros (garrafas, botellas…)',
    count: 'Por piezas',
    countSub: 'Unidades sueltas (huevos, bolsas de 1 ud…)',
  },
  amounts: {
    title: '¿Cuánto pagáis?',
    hint: 'Poned el importe tal cual en la factura. Si es caja, en el siguiente bloque repartimos entre lo que trae dentro.',
    priceEur: 'Importe en euros',
    priceSimpleHint: 'Tal como en la factura: euros por kilo, por litro o por unidad.',
    packFullPrice: 'Precio de toda la caja o pack',
    howManyInPack: '¿Cuántas piezas trae ese pack?',
    howManyInPackHint: 'Ejemplo: 24 si son 24 latas dentro de la caja.',
    eachPiece: '¿Cuánto lleva cada pieza?',
    eachPieceHint: 'Ejemplo: 330 y mililitros si la lata pone 330 ml. Si son piezas sueltas sin peso, 1 y «ud».',
    shortcuts: 'Atajos habituales',
    noPerPiece: 'Cada pieza cuenta como 1 unidad (no hace falta peso ni ml).',
    costPreview: 'Coste por unidad de receta (calculado)',
    skipLater: 'Sin precio aún',
    save: 'Guardar y seguir',
  },
  modal: {
    header: 'Ayuda para el precio',
    step: (n: 1 | 2, total: 2) => `Pregunta ${n} de ${total}`,
    done: 'Listo',
  },
  express: {
    title: 'Precio del producto',
    hint: 'Usamos el importe del albarán. Elige solo cómo cobra el proveedor; el resto lo calculamos.',
    invoiceBanner: 'Datos del albarán',
    priceLabel: 'Importe en la factura (€)',
    chargeBy: 'El proveedor cobra por',
    perKg: 'Kilo',
    perKgSub: '€/kg en factura',
    perL: 'Litro',
    perLSub: '€/litro en factura',
    perBottle: 'Botella o unidad',
    perBottleSub: 'Cada pieza con su tamaño (vino, latas…)',
    perBox: 'Caja o pack',
    perBoxSub: 'Un precio para todo el bulto',
    bottleSize: '¿Cuánto trae cada unidad?',
    boxCount: 'Piezas en la caja',
    recipeCost: 'Coste en recetas',
    mapFactor: 'Factor sugerido al guardar el vínculo',
    save: 'Guardar precio',
    advanced: 'Más opciones…',
    nameLabel: 'Nombre en almacén',
  },
} as const
