create table if not exists public.camera_external_connection_sessions (
  id bigint generated by default as identity primary key,
  camera_id text not null,
  started_at timestamptz not null,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  constraint camera_external_connection_sessions_time_check check (ended_at is null or ended_at >= started_at)
);

create unique index if not exists camera_external_connection_sessions_one_open_per_camera
  on public.camera_external_connection_sessions (camera_id)
  where ended_at is null;

create index if not exists camera_external_connection_sessions_camera_started_idx
  on public.camera_external_connection_sessions (camera_id, started_at desc);

alter table public.camera_external_connection_sessions enable row level security;
revoke all on table public.camera_external_connection_sessions from anon, authenticated;
revoke all on sequence public.camera_external_connection_sessions_id_seq from anon, authenticated;

comment on table public.camera_external_connection_sessions is 'Server-only history of external camera viewer sessions.';
